### ISSUE TITLE
World data load bug

### ISSUE THREAD

**Issue by Yossarian82** [sungaila/SurvivalNotRequired#1]
I seem to have a bug here: https://ibb.co/kyKCLn7

When I spawn a new world for the first time, it works ok. If I go back to the main menu and spawn a new world again, the bug shown in the picture occurs.

My modlist:

Mod Manager
Queue for Sinks
More Marble Structures
Missing Element Textures
Airlock Door
Fast Save
Forbid Items
GasOverlay
DGSM
Survival Not Required

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

This bug also occurs after the following sequence of events:

1) Generate world and arrive at initial dupe selection screen
2) Back out to the main menu
3) Generate world and arrive at initial dupe selection screen
4) Back out to the main menu
5) Crash to desktop

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Suggestion from another mod author:

Aki: "they accidentally apply the template modifications at every world data load, instead of once per game load. 
should be an easy fix, its a simple oversight."

**Comment by sungaila** [comment]
Hi @Yossarian82,

thank you for finding and reporting this bug! Aki was right about the source of this issue: I patched the world templates every time a world is generated. A simple check to avoid patching more than once fixed this. :-)

Version 1.1.1 is live on Steam Workshop, please give it a try!
